micronaut:
  application:
    name: dcc-bot
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/cuca
    username: sa
    password: sa
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 10
jpa.default:
  properties.hibernate.hbm2ddl.auto: create-drop
  entity-scan.packages: 'dev.softawii.entity'